nacos:
  config:
    #是否开启Nacos配置预加载
    bootstrap:
      enable: true
    data-id: demo-boot-v3
    type: yaml
    group: sever-provide
    auto-refresh: true
    server-addr: 127.0.0.1:8848
    namespace: 5510f6f2-67cb-438a-bca5-06d5d187d6c1


zzw:
  rpc:
    app-port: 8888
    netty-port: 7777
    service-address: 192.168.1.15

spring:
  application:
    name: sever

server:
  port: 8888
