nacos:
  config:
    #是否开启Nacos配置预加载
    bootstrap:
      enable: true
    data-id: demo-boot-v3
    type: yaml
    group: sever-provide
    auto-refresh: true
    server-addr: 127.0.0.1:8848
    namespace: b0f67995-fe9f-4438-a8a9-b1589fa0bb44


rpc:
  netty:
    sever:
      ipaddr: 127.0.0.1
      port: 7777
  address: 127.0.0.1
  port: 8888

zzw:
  rpc:
    app-port: 8888
    netty-port: 7777
    service-address: localhost

spring:
  application:
    name: sever

server:
  port: 8888
