nacos:
  config:
    #是否开启Nacos配置预加载
    bootstrap:
      enable: true
    data-id: demo-boot-v3
    type: yaml
    group: sever-provide
    auto-refresh: true
    server-addr: 127.0.0.1:8848
    namespace: 5510f6f2-67cb-438a-bca5-06d5d187d6c1

